[package]
name = "imgid"
version = "0.1.0"
authors = ["Yury Konovalov <YKonovalov@gmail.com>"]
edition = "2018"

[dependencies]
hex = "*"

[dependencies.image]
version = ">=0.10, <=0.19"

[dependencies.img_hash]
version = "2.0"
# For interop with `image`:
features = ["rust-image"]